// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	proto/auth/auth.proto

It has these top-level messages:
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import general "github.com/LarsMiren/accountancy/proto/general"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *general.User, opts ...grpc.CallOption) (*general.User, error)
	Logout(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*general.Confirmation, error)
	Signup(ctx context.Context, in *general.User, opts ...grpc.CallOption) (*general.Confirmation, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *general.User, opts ...grpc.CallOption) (*general.User, error) {
	out := new(general.User)
	err := grpc.Invoke(ctx, "/auth.auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*general.Confirmation, error) {
	out := new(general.Confirmation)
	err := grpc.Invoke(ctx, "/auth.auth/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Signup(ctx context.Context, in *general.User, opts ...grpc.CallOption) (*general.Confirmation, error) {
	out := new(general.Confirmation)
	err := grpc.Invoke(ctx, "/auth.auth/Signup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *general.User) (*general.User, error)
	Logout(context.Context, *google_protobuf1.Empty) (*general.Confirmation, error)
	Signup(context.Context, *general.User) (*general.Confirmation, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(general.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*general.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(general.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.auth/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Signup(ctx, req.(*general.User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _Auth_Signup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth/auth.proto",
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x86, 0x39, 0xd1, 0x14, 0xf1, 0x03, 0x5d, 0xbc, 0x13, 0xa2, 0x55, 0xca, 0x14, 0x3b, 0xa0,
	0xdd, 0xc1, 0x35, 0x8a, 0xd8, 0xe4, 0x2a, 0xb1, 0xb1, 0xdb, 0x84, 0xbd, 0xbd, 0x85, 0x64, 0x26,
	0xec, 0x47, 0x71, 0xad, 0x7f, 0xc1, 0x9f, 0x66, 0x6d, 0xe7, 0x0f, 0x91, 0x4c, 0xd6, 0x03, 0x05,
	0x9b, 0x65, 0x5f, 0x66, 0xde, 0x87, 0x67, 0xf2, 0xf9, 0xe0, 0x28, 0x10, 0xa8, 0x18, 0xb6, 0xfc,
	0x48, 0xce, 0xe2, 0x70, 0xfc, 0x17, 0x37, 0x86, 0xc8, 0x74, 0x1a, 0xd4, 0x60, 0x41, 0x21, 0x52,
	0x50, 0xc1, 0x12, 0xfa, 0x69, 0xa7, 0xb8, 0x4e, 0x53, 0x4e, 0x4d, 0xdc, 0x80, 0xee, 0x87, 0xb0,
	0x4b, 0xc3, 0x95, 0xb1, 0x61, 0x1b, 0x1b, 0xd9, 0x52, 0x0f, 0xb5, 0x72, 0x7e, 0x6d, 0x9d, 0x46,
	0x50, 0x6d, 0x4b, 0x11, 0x83, 0xc2, 0x76, 0x37, 0xd5, 0xc0, 0x68, 0xd4, 0x4e, 0x75, 0xd0, 0x6b,
	0xef, 0x95, 0xd1, 0x89, 0x7d, 0xfb, 0x39, 0xcb, 0x59, 0x41, 0xac, 0xf2, 0xa3, 0x9a, 0x8c, 0x45,
	0x71, 0x2a, 0xd3, 0xaa, 0x7c, 0xf1, 0xda, 0x15, 0xbf, 0x63, 0xb9, 0x78, 0xfb, 0xf8, 0x7a, 0x3f,
	0x38, 0x2f, 0x8f, 0x21, 0x7a, 0xed, 0xa0, 0x1b, 0x2b, 0xcb, 0x59, 0x25, 0xd6, 0x79, 0x56, 0x93,
	0xa1, 0x18, 0xc4, 0x42, 0x4e, 0xba, 0xf2, 0x47, 0x57, 0x3e, 0x8e, 0xba, 0xc5, 0x7c, 0x0f, 0x7a,
	0x20, 0xdc, 0x58, 0xd7, 0xf3, 0x8d, 0xe5, 0x25, 0x03, 0xcf, 0xaa, 0x93, 0x3d, 0x70, 0x84, 0x3c,
	0xe5, 0xd9, 0xb3, 0x35, 0x18, 0x87, 0xbf, 0x3a, 0xff, 0x50, 0xae, 0x98, 0x72, 0x51, 0x26, 0x8a,
	0xe7, 0xee, 0x72, 0x56, 0xdd, 0x67, 0xaf, 0x7c, 0x5e, 0x93, 0xb1, 0xcd, 0xdd, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0x0f, 0x60, 0xfd, 0x87, 0x01, 0x00, 0x00,
}
