// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/general/messages.proto

/*
Package general is a generated protocol buffer package.

It is generated from these files:
	proto/general/messages.proto

It has these top-level messages:
	User
	Confirmation
*/
package general

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id           string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Username     string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	PersonalData string `protobuf:"bytes,5,opt,name=personalData" json:"personalData,omitempty"`
	Password     string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPersonalData() string {
	if m != nil {
		return m.PersonalData
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Confirmation struct {
	Confirm bool   `protobuf:"varint,1,opt,name=confirm" json:"confirm,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Confirmation) Reset()                    { *m = Confirmation{} }
func (m *Confirmation) String() string            { return proto.CompactTextString(m) }
func (*Confirmation) ProtoMessage()               {}
func (*Confirmation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Confirmation) GetConfirm() bool {
	if m != nil {
		return m.Confirm
	}
	return false
}

func (m *Confirmation) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "general.User")
	proto.RegisterType((*Confirmation)(nil), "general.Confirmation")
}

func init() { proto.RegisterFile("proto/general/messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x3f, 0x4a, 0xc7, 0x40,
	0x10, 0x85, 0x49, 0xcc, 0x2f, 0x7f, 0x86, 0x60, 0x31, 0x58, 0x2c, 0x62, 0x21, 0xa9, 0xac, 0x4c,
	0xe1, 0x0d, 0xa2, 0x27, 0x08, 0xd8, 0xd8, 0x8d, 0x66, 0x0c, 0x0b, 0xd9, 0xdd, 0xb0, 0x13, 0xf1,
	0x32, 0x1e, 0x56, 0x32, 0xc9, 0x0a, 0x76, 0xfb, 0x7d, 0x6f, 0x07, 0xde, 0x83, 0xbb, 0x35, 0x86,
	0x2d, 0xf4, 0x33, 0x7b, 0x8e, 0xb4, 0xf4, 0x8e, 0x45, 0x68, 0x66, 0x79, 0x54, 0x8d, 0xd5, 0xe9,
	0xbb, 0x9f, 0x0c, 0x8a, 0x57, 0xe1, 0x88, 0xd7, 0x90, 0xdb, 0xc9, 0x64, 0xf7, 0xd9, 0x43, 0x33,
	0xe6, 0x76, 0x42, 0x84, 0xc2, 0x93, 0x63, 0x93, 0xab, 0xd1, 0x37, 0xde, 0xc0, 0x85, 0x1d, 0xd9,
	0xc5, 0x5c, 0xa9, 0x3c, 0x00, 0x6f, 0xa1, 0xfe, 0x12, 0x8e, 0xfa, 0xbb, 0xd0, 0xe0, 0x8f, 0xb1,
	0x83, 0x76, 0xe5, 0x28, 0xc1, 0xd3, 0xf2, 0x42, 0x1b, 0x99, 0x8b, 0xe6, 0xff, 0xdc, 0x7e, 0xbf,
	0x92, 0xc8, 0x77, 0x88, 0x93, 0x29, 0x8f, 0xfb, 0xc4, 0xdd, 0x00, 0xed, 0x73, 0xf0, 0x9f, 0x36,
	0x3a, 0xda, 0x6c, 0xf0, 0x68, 0xa0, 0xfa, 0x38, 0x58, 0xab, 0xd6, 0x63, 0xc2, 0x3d, 0x39, 0x37,
	0x9e, 0x95, 0x13, 0x0e, 0xcd, 0x5b, 0x5a, 0xfb, 0x5e, 0xea, 0xfa, 0xa7, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2e, 0x04, 0xc5, 0x26, 0x1d, 0x01, 0x00, 0x00,
}
